//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Dental_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaBinhLuan
    {
        public long Id_DanhGia { get; set; }
        public Nullable<double> DiemDanhGia { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<int> IDBACSI { get; set; }
    
        public virtual NhaSi NhaSi { get; set; }
    }
}
