//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Dental_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DienDan
    {
        public int Id_diendan { get; set; }
        public string title { get; set; }
        public string img { get; set; }
        public string content { get; set; }
        public string img2 { get; set; }
        public string content2 { get; set; }
    }
}
